# Default image (https://hub.docker.com/_/node)
image: node:18-bullseye

# Stages: lint -> test -> docker -> deploy
stages:
  - lint
  - test
  - docker
  - deploy

# Cached files between builds
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

# Dependency scanning & SAST
include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml

# ESLint
eslint:
  stage: lint
  before_script:
    - npm ci
  script:
    - npm run lint
  allow_failure: true

# Build
.build:
  stage: test
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

build_staging:
  extends: .build
  script:
    - echo "$CD_STAGING_ENV" > .env.production.local
    - echo "$CD_BRANDING" > public/branding.json
    - npm run build
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PROJECT_NAMESPACE == "tms-elte"'

build_production:
  extends: .build
  script:
    - echo "$CD_PRODUCTION_ENV" > .env.production.local
    - echo "$CD_BRANDING" > public/branding.json
    - npm run build
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v[^-]*$/ && $CI_PROJECT_NAMESPACE == "tms-elte"'

# Docker login credentials (similar to backend)
.docker-login: &docker-login
  - docker version
  # Login to Docker Hub and GitLab Container Registry
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_TOKEN"

# Docker build and push for frontend
.docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_COMMIT_REF_NAME
  before_script:
    - *docker-login
  script:
    # Build the Docker image for the frontend
    - docker build . --pull -t "tmselte/frontend-react:$IMAGE_TAG" -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
    # Push the Docker image to the registry
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
    - docker push "tmselte/frontend-react:$IMAGE_TAG"

# Build and push Docker image for the 'latest' tag (for the master branch)
docker_latest:
  extends: .docker
  variables:
    IMAGE_TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PROJECT_NAMESPACE == "tms-elte"

# Build and push Docker image for 'nightly' builds (for the develop branch)
docker_nightly:
  extends: .docker
  variables:
    IMAGE_TAG: nightly
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" && $CI_PROJECT_NAMESPACE == "tms-elte"

# Build and push Docker image for specific version tags (similar to backend)
docker_version:
  extends: .docker
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG
  before_script:
    - *docker-login
    # Remove v prefix from tag (same as backend)
    - IMAGE_TAG=${IMAGE_TAG#v}
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v[^-].*$/ && $CI_PROJECT_NAMESPACE == "tms-elte"'

# Deployment over SSH
.deploy:
  stage: deploy
  image: ubuntu:20.04
  variables:
    DEPLOY_PATH: /var/www/html
    TEMP_PATH: /tmp/tms_frontend_react_$CI_COMMIT_SHORT_SHA/
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$CD_PRIVATE_KEY")
    - ssh -P22 gitlab-deployer@tms.inf.elte.hu "rm -rf $TEMP_PATH"
    - ssh -P22 gitlab-deployer@tms.inf.elte.hu "mkdir -p $TEMP_PATH/new"
    - scp -P22 -r build gitlab-deployer@tms.inf.elte.hu:$TEMP_PATH/new
    - ssh -P22 gitlab-deployer@tms.inf.elte.hu "mv $DEPLOY_PATH $TEMP_PATH/old && mv $TEMP_PATH/new/build $DEPLOY_PATH"
    - ssh -P22 gitlab-deployer@tms.inf.elte.hu "rm -rf $TEMP_PATH"

# Deployment to staging environment of ELTE
# All pushes on develop
deploy_staging:
  extends: .deploy
  dependencies:
    - build_staging
  variables:
    DEPLOY_PATH: /var/www/tms_dev/frontend-react/
  environment:
    name: staging
    url: https://tms.inf.elte.hu/dev/
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PROJECT_NAMESPACE == "tms-elte"'

# Deployment to production environment of ELTE
# All v* tags, excluding prereleases
deploy_production:
  extends: .deploy
  dependencies:
    - build_production
  variables:
    DEPLOY_PATH: /var/www/tms_prod/frontend-react/
  environment:
    name: production
    url: https://tms.inf.elte.hu/
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v[^-]*$/ && $CI_PROJECT_NAMESPACE == "tms-elte"'
